import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { routing } from "../../i18n/routing";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import Navigation from "../../components/Navigation";
import { Toaster } from "sonner";
import SonnerNextIntlProvider from "../../components/SonnerNextIntlProvider";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return (
    <html className="h-full" lang={locale}>
      <body className={`flex h-full flex-col ${inter.className}`}>
        <NextIntlClientProvider>
          <SonnerNextIntlProvider>
            <Toaster closeButton richColors />
            <Navigation />
            {children}
          </SonnerNextIntlProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
